### ISSUE TITLE
Hardcoded Strings Untranslatable

### ISSUE THREAD

**Issue by WuzgXY-GitHub** [Jedibrine/pouchviewer#1]
Could you make the entries of config and tooltips translatable, so that players speaking other languages are able to enjoy the mod better?

**Comment by MagmaBro123** [comment]
A Discord does exist, if you wish to join. https://discord.gg/XBx8CVV4CY

**Comment by Jedibrine** [comment]
I'll work on it

**Comment by Jedibrine** [comment]
I'm going to be pretty busy for a few months, sorry :(

If anyone else wants to implement this, feel free

**Comment by Jedibrine** [comment]
Closed due to transition to visual tooltip
All phrases used in visual tooltip use lotr lang files with the next release
