### ISSUE TITLE
Pouch items appear under inventory items

### ISSUE THREAD

**Issue by DarianLStephens** [Jedibrine/pouchviewer#3]
As said in the title, the items rendered as part of the pouch's tooltip are shown under other inventory items.
![2023-03-31_05 09 17](https://user-images.githubusercontent.com/15375876/228926307-73f9c5ef-0a4d-4b0a-9d2a-06c92c0837ad.png)

Additionally, it would be nice if the tooltip could only show items that exist in the pouch, instead of also showing empty slots, and maybe a background like the Bundle's renderer?

**Comment by MagmaBro123** [comment]
Jedi isn’t the best modder, and the GUI system is kinda buggy.

**Comment by Jedibrine** [comment]
fixed in new version I'll upload it soon

**Comment by DarianLStephens** [comment]
Awesome to see this out!
It does seem that items are lacking their shading, though. Mostly blocks:
![2023-04-07_14 41 16](https://user-images.githubusercontent.com/15375876/230542264-46fc2f76-9f94-45b3-85ac-3fb4008889b9.png)

And, umm...
![2023-04-07_14 41 27](https://user-images.githubusercontent.com/15375876/230542315-74821c97-9be9-4d42-9f45-f5441ef0f626.png)
???

**Comment by MagmaBro123** [comment]
I've noticed the bottom issue as well.

**Comment by DarianLStephens** [comment]
Oh, also, is there an option yet to enable that background? I saw it mentioned in the changelog, but can't find anything.
Additionally, the 'hide empty slots' option doesn't appear in an old config, only a freshly-generated one. Not a big issue, but worth noting maybe?

If it helps with the 'Unnamed' issue, that bad was owned by someone previously, and I have the option to remove that line disabled.

**Comment by Jedibrine** [comment]
- Blocks shading should be fixed in new release
- No option to enable the background yet since its still a bit ugly, will try to implement this by next release after the bugs are fixed
- I thought that configs might be an issue, just delete the old one for now and I'll try to overhaul the config in the future
- For the unnamed issue, I can't replicate it in the debug client but I can on a fresh Forge profile, so it might take some extra time to fix. Do you know if this issue was present in 2.0?

**Comment by DarianLStephens** [comment]
It was not an issue in 2.0.
I do vaguely recall a similar issue earlier in the mod's history, but I could be mistaken.

**Comment by Jedibrine** [comment]
Yeah the unnamed pouch text becomes an issue when something weird happens to the tooltip, it should be patched in the next release

**Comment by MagmaBro123** [comment]
@DarianLStephens Jedi also has a Discord, if you wish to join.

**Comment by Jedibrine** [comment]
All issues discussed are fixed with the new version, so closing this
