### ISSUE TITLE
Depth issue with hollow items

### ISSUE THREAD

**Issue by mist475** [Jedibrine/pouchviewer#5]
![2023-06-12_12 25 01](https://github.com/Jedibrine/pouchviewer/assets/70655895/f180c212-f15e-40b9-8103-235692f9ecd6)
Chests and the like render wrong when the preview is enabled

**Comment by Jedibrine** [comment]
tile entities with depth mask disabled render the faces backwards. however, if depth mask is enabled then the tile entities render behind other items in the inventory. currently looking for a way but I'm busy with moving so we will see

**Comment by Jedibrine** [comment]
Fixed with 2.4.2
